pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = "AKIA6ODU35FAWNDBZ7O6"
        AWS_SECRET_ACCESS_KEY = "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"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'pradeep/gen2', url: 'https://github.com/Pradeep-VJ/astra-test-code.git'
            }
        }

        stage('Setup Environment') {
            steps {
                sh 'sudo yum install -y python3 python3-pip'
                sh 'pip3 install -r lambda/requirements.txt'
            }
        }

        stage('Build Lambda Package') {
            steps {
                dir('lambda') {
                    sh 'chmod +x build_lambda.sh'
                    sh './build_lambda.sh'
                }
            }
        }

        stage('Deploy Lambda with Terraform') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
