pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'pradeep/gen1', url: 'https://github.com/Pradeep-VJ/astra-test-code.git'
            }
        }
        stage('Install Python & pip') {
            steps {
                sh '''
                sudo yum install python3 -y
                sudo yum install python3-pip -y
                '''
            }
        }
        stage('Build Lambda Package') {
            steps {
                dir('lambda') {
                    sh '''
                    chmod +x build_lambda.sh
                    ./build_lambda.sh
                    '''
                }
            }
        }
        stage('Terraform Init & Apply') {
            steps {
                dir('terraform') {
                    sh '''
                    terraform init
                    terraform apply -auto-approve \
                        -var="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
                        -var="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
                    '''
                }
            }
        }
        stage('Deploy Lambda') {
            steps {
                dir('lambda') {
                    sh '''
                    chmod +x deploy_lambda.sh
                    ./deploy_lambda.sh
                    '''
                }
            }
        }
    }
}
